/*
 * Auto-generated by tools/build-preload-debs.sh — DO NOT EDIT BY HAND.
 * Re-run the script to regenerate.
 */
#ifndef DOPAMINE_PRELOAD_DEBS_H
#define DOPAMINE_PRELOAD_DEBS_H

static NSString * const kDopaminePreinstalledDebs[] = {
    @"preload-00-ellekit.deb",
    @"preload-10-hooks.deb",
};
static const size_t kDopaminePreinstalledDebsCount =
    sizeof(kDopaminePreinstalledDebs) / sizeof(kDopaminePreinstalledDebs[0]);

#endif /* DOPAMINE_PRELOAD_DEBS_H */
